### ISSUE TITLE
User Model

### ISSUE THREAD

**Issue by tsgbeck** [ChristianDeGuzmanUF/CEN3031_Team4#1]
Team,

I created a [userAuth branch](https://github.com/ChristianDeGuzmanUF/CEN3031_Team4/tree/userAuth), for developing the backend and initial front-end routing of the user login and registration page. Please review the [UserSchema](https://github.com/ChristianDeGuzmanUF/CEN3031_Team4/blob/userAuth/server/models/UserSchema.js), particularly whether we want all or only some of the following for a user:

* First Name
* Last Name
* login name (userName)
* email address

Thanks,
tsg

**Comment by kdewey13** [comment]
I am not seeing email in the schema currently? I would say yes to it being there, but optional. All the other attributes look good to me, and I can't think of more that are needed. 

Also probably a question for later, but should there be password constraints in the schema?

**Comment by tsgbeck** [comment]
> I am not seeing email in the schema currently? I would say yes to it being there, but optional. All the other attributes look good to me, and I can't think of more that are needed.
> 
> Also probably a question for later, but should there be password constraints in the schema?

I can add email if we want it to be in there. Pedro has email for password recovery in the wireframe, so we'll have to decide if this is something we'll need to require during account creation. If not email, maybe  a recovery would send a notice/teacher to a teacher. Thoughts here?

Given there's no PII, or other critical data... I'm open to what password constraints should be. I assume if they're too rigid we'll be dealing with a lot of recoveries... (or the app will be).
